In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Karan\Downloads\netflix_titles.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [ ]:
import numpy as np
idk = df['country'].str.split(',').explode().replace('',np.nan).dropna().str.strip().sort_values().unique()
idk1 = pd.Series(idk)
idk1.count()
idk1

#countries were repeating because i didnt strip the ones that were split.... bye

0               Afghanistan
1                   Albania
2                 Argentina
3                   Armenia
4                 Australia
5                   Austria
6                Azerbaijan
7                Bangladesh
8                   Belgium
9                   Bermuda
10                 Botswana
11                   Brazil
12                 Bulgaria
13                 Cambodia
14                   Canada
15           Cayman Islands
16                    Chile
17                    China
18                 Colombia
19                  Croatia
20                     Cuba
21                   Cyprus
22           Czech Republic
23                  Denmark
24       Dominican Republic
25             East Germany
26                  Ecuador
27                    Egypt
28                  Finland
29                   France
30                  Georgia
31                  Germany
32                    Ghana
33                   Greece
34                Guatemala
35                Hong Kong
36                  Hungary
37                  Iceland
38                    India
39                Indonesia
40                     Iran
41                     Iraq
42                  Ireland
43                   Israel
44                    Italy
45                    Japan
46                   Jordan
47               Kazakhstan
48                    Kenya
49                   Kuwait
50                   Latvia
51                  Lebanon
52            Liechtenstein
53               Luxembourg
54                   Malawi
55                 Malaysia
56                    Malta
57                Mauritius
58                   Mexico
59                 Mongolia
60               Montenegro
61                  Morocco
62                  Namibia
63                    Nepal
64              Netherlands
65              New Zealand
66                Nicaragua
67                  Nigeria
68                   Norway
69                 Pakistan
70                   Panama
71                 Paraguay
72                     Peru
73              Philippines
74                   Poland
75                 Portugal
76                    Qatar
77                  Romania
78                   Russia
79                    Samoa
80             Saudi Arabia
81                  Senegal
82                   Serbia
83                Singapore
84                 Slovakia
85                 Slovenia
86                  Somalia
87             South Africa
88              South Korea
89             Soviet Union
90                    Spain
91                Sri Lanka
92                    Sudan
93                   Sweden
94              Switzerland
95                    Syria
96                   Taiwan
97                 Thailand
98                   Turkey
99                   Uganda
100                 Ukraine
101    United Arab Emirates
102          United Kingdom
103           United States
104                 Uruguay
105            Vatican City
106               Venezuela
107                 Vietnam
108            West Germany
109                Zimbabwe
dtype: str

In [76]:
content_type = df['type'].dropna().unique()
fil_df = df[df['type'].isin(content_type)]
fil_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [89]:
df[df['country'].isin([''," "])]
#so there is no row in country with a blank item....oK

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []